### ISSUE TITLE
extra install steps to make audio.py run

### ISSUE THREAD

**Issue by jeffalexander** [pirate/mac-hardware-toys#4]
Love this utility. Currently blinking along to Days of the New.

I had not previously installed many python libs so the README.md step was not enough to get audio.py to run.

Error:
```
$ pip3 install --upgrade pyaudio audioop
Collecting pyaudio
  Downloading PyAudio-0.2.11.tar.gz
Collecting audioop
  Could not find a version that satisfies the requirement audioop (from versions: )
No matching distribution found for audioop
```

Fix:
```
brew install python3
brew install portaudio
pip3 install pyaudio
```

Then like the README says:
```
python3 audio.py
```

Refs:
https://stackoverflow.com/questions/31236194/installing-pyaudio-for-python3-on-osx

**Comment by pirate** [comment]
Thanks, closed: https://github.com/pirate/mac-keyboard-brightness/commit/b6410c160d73a4432dea18d792456df0534672d1
