### ISSUE TITLE
Sets keyboard brightness only temporarily  

### ISSUE THREAD

**Issue by sevenmaxis** [pirate/mac-hardware-toys#7]
I set the keyboard brightness to 0
`./kbrightness 0`
Press the power button to sleep, wake the mac up and then I get 100% brightness for keyboard.
Is this a desirable behavior? How to set key brightness permanently?

**Comment by pirate** [comment]
Dunno, not something we really have control over using the system API.  You can set up an onwake script trigger to reset it.

https://stackoverflow.com/questions/35488690/run-apple-script-after-mac-resumes-from-sleep-mode
https://www.dssw.co.uk/blog/2011-02-01-how-to-run-an-applescript-on-wake-up/
https://forums.macrumors.com/threads/run-apple-script-on-wake-up.1975653/
